### ISSUE TITLE
review: aaa_clean_linelist

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/report_factories_templates#10]
We need a review for the *aaa_clean_linelist* report.

Quick links to:

golden rules for writing reports: https://github.com/reconhub/guides/raw/master/golden_rules.html.zip

guide to review:
https://github.com/reconhub/report_factories_templates#revewing-changes

**Comment by kya2** [comment]
For consideration:
https://github.com/reconhub/report_factories_templates/issues/6

**Comment by jarvisc1** [comment]
Looks good. I guess this has been reviewed by many people already.  A few small comments:

# Data cleaning

## aliases and renaming
- [ ]  Add in other date variables to have date at the start of the name

## identify community death
- [ ] Consider issue number #6  re @kya2 

-## Reorder columns
[ ]  Remove commented out columns in the reordering of columns lines 459

**Comment by jarvisc1** [comment]
Adding the hospital dates to the cleaning causes some issues. It's related to the tolerance of the number of dates it's unable to clean. 

This might not be resolved here and require looking at the master linelist. I tried changing the tolerance to 0.99 and it still failed.

**Comment by jarvisc1** [comment]
To add 

- [ ]  A section on the report saying here are areas where we haven't received any alerts in the last 3 weeks
- [ ]  Here are area where we have never received any reports
- [ ]  Get a list of all the aire_de_santes
