### ISSUE TITLE
review: active_health_area

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/report_factories_templates#12]
We need a review for the *active_health_area* report.

Quick links to:

golden rules for writing reports: https://github.com/reconhub/guides/raw/master/golden_rules.html.zip

guide to review:
https://github.com/reconhub/report_factories_templates#revewing-changes

**Comment by thibautjombart** [comment]
Suggested addition: define a custom color palette for the sub-coordinations; the current one has too many similar colors that are hard to tease apart; maybe best use the color palette defined in the *epicurves* report.

**Comment by ffinger** [comment]
PR in #22
