### ISSUE TITLE
review: alerts_goma

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/report_factories_templates#15]
We need a review for the report `alerts_goma` in the *alerts* factory. This report will become the basic template for other alerts which are currently broken following additions over the summer (incidence of alerts, use of population data).

It also would be nice to re-add the alerts by validation, down to health areas. If so we should extract code from the currently broken reports and re-add Charlie Whittaker as co-author / code contributor.

Quick links to:

golden rules for writing reports: https://github.com/reconhub/guides/raw/master/golden_rules.html.zip

guide to review:
https://github.com/reconhub/report_factories_templates#revewing-changes

**Comment by jarvisc1** [comment]
Have decided to change to taking the current report and making it work. Removing out population stuff for the moment. Perhaps it can be readded later.

**Comment by jarvisc1** [comment]
To add 

- [ ]  A section on the report saying here are areas where we haven't received any alerts in the last 3 weeks
- [ ]  Here are area where we have never received any reports
- [ ]  Get a list of all the aire_de_santes

**Comment by jarvisc1** [comment]
- [ ] Adding in the alerts rates and population data

**Comment by jarvisc1** [comment]
- [ ] Added in rates info as well. 

- [ ] Remove rates section if not pop data present.
