### ISSUE TITLE
Temporal trends: additional analyses

### ISSUE THREAD

**Issue by kya2** [reconhub/report_factories_templates#4]
I would like to add these reports on the temporal reportfactory:

- [x]	Contacts followed, general and stratified
- [x]	Number of HCWs, general and stratified
- [x]	Add top zones stratification to the existing reports

What do you think?

**Comment by thibautjombart** [comment]
Yes to all, with the caveat that for trends, proportion of HCW rather than raw numbers would be safer (people might infer decreases / increases in raw numbers while the proportion actually does not change)

**Comment by kya2** [comment]
I sent a pull request earlier today for the first and third bullet points. I am thinking more about the second bullet point and your comment. Merci.

**Comment by thibautjombart** [comment]
Thanks for the heads up. I'll try and get to it tomorrow afternoon.

**Comment by thibautjombart** [comment]
Poke on this, with the following update (UNICEF request):

- [ ] % of HCW
- [ ] % of nosocomial infections

**Comment by kya2** [comment]
HCW ready for review

**Comment by thibautjombart** [comment]
@kya2 useful tip: you can refer to the PR here by adding its url (github will display it in an adaptaed way); this makes the system (and others) aware of cross-referencing; so you can say:

- [x] % HCW: see PR https://github.com/reconhub/report_factories_templates/pull/14 , ready to review

**Comment by thibautjombart** [comment]
Closed via https://github.com/reconhub/report_factories_templates/pull/16
