### ISSUE TITLE
Proposed changes to place_death_crude in MLL cleaning rules

### ISSUE THREAD

**Issue by kya2** [reconhub/report_factories_templates#6]
Here are the variables in the MLL for place of death:

- place_of_death = {null, community, hcf, hospital, other_hcf, other, etc, tc, unknown}
- place_death_crude = {community, etc, unknown}; no null--alive is coded as “unknown”
- type_death = {alive, community, etc_tc, unknown); no null
- community_death = {1,0}; no null

type_death is used to calculate community deaths, so it combines community, hcf, etc. into community (as it should)

However, with these variables, we cannot analyse hcf deaths, which is of interest to the IPC Commission. I propose we make two changes to place_death_crude:

- Recode {hcf, hospital, other_hcf} as "community_hcf" or "hcf"
- Recode living (currently a subset of the "unknown") as "alive"

The first can occur easily by changing three cells in cleaning_rules.xlsx from "community" to "community_hcf" (variable: place_death_crude). The second (unknown to alive) needs to be changed in the code where place_death_crude is (re)defined.

**Comment by jarvisc1** [comment]
Resolved with #19 but didn't close automativally
